@startuml
!theme blueprint
skinparam componentStyle rectangle
skinparam defaultFontName Roboto
skinparam linetype ortho
skinparam nodesep 5
skinparam ranksep 1
top to bottom direction

title Architecture d'une appplication native

rectangle "Application" as YourApp {
    [{ ; }] as N1
    [{ ; }] as N2
    [{ ; }] as N3   
    [{ ; }] as N4
}

rectangle "Platform" as Platform {
    rectangle "UI" as L1 {
        [OEM Widgets] as OEM
        together {
            [Canvas] as Canvas
            [Events] as Events
        }

        OEM -r-> Canvas
        OEM -r-> Events
        Canvas -[hidden]- Events
    }


    rectangle "API" as L2 {
        [Location] as Location
        [Camera] as Camera
        [Bluetooth] as Bluetooth
    }
 
    L1 -[hidden]d--- L2
}

YourApp <-r-> L1
YourApp <-r-> L2


@enduml